[book]
authors = ["David Thrane Christiansen"]
language = "en"
multilingual = false
src = "src"
title = "Functional Programming in Lean"

[build]

[preprocessor.leanexample]
command = "python scripts/example.py"

[preprocessor.commands]
command = "python scripts/projects.py"


[output.html]
additional-css = ["custom.css"]

#[output.pandoc]
#command = "python ../../scripts/one-markdown.py"

[output.wordcount]
